AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  LoyaltyCardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: LoyaltyCards
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
  GetLoyaltyCardsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.getLoyaltyCards
      Runtime: nodejs22.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LoyaltyCardsTable
      Environment:
        Variables:
          LOYALTY_CARDS_TABLE: LoyaltyCards
          DYNAMODB_ENDPOINT: http://dynamodb:8000
      Events:
        GetLoyaltyCard:
          Type: Api
          Properties:
            Path: /loyalty-cards
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  GetLoyaltyCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.getLoyaltyCard
      Runtime: nodejs22.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LoyaltyCardsTable
      Environment:
        Variables:
          LOYALTY_CARDS_TABLE: LoyaltyCards
          DYNAMODB_ENDPOINT: http://dynamodb:8000
      Events:
        GetLoyaltyCard:
          Type: Api
          Properties:
            Path: /loyalty-cards/{id}
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  CreateLoyaltyCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.createLoyaltyCard 
      Runtime: nodejs22.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LoyaltyCardsTable
      Environment:
        Variables:
          LOYALTY_CARDS_TABLE: LoyaltyCards
          DYNAMODB_ENDPOINT: http://dynamodb:8000
      Events:
        CreateLoyaltyCard:
          Type: Api
          Properties:
            Path: /loyalty-cards
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

