include classpath("application.conf")

node-address {
  protocol = http
  host = "0.0.0.0"
  port = 9324
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
}

queues {
  loyalty-cards {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
}
